# Generated by Django 5.1.3 on 2024-11-30 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterModelTable(
            name='libro',
            table='libros',
        ),
    ]
